# Generated by Django 5.2.14 on 2026-06-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('church_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Church ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='姓名')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='地址')),
                ('mobile1', models.CharField(blank=True, default='', max_length=50, verbose_name='手機')),
                ('email1', models.CharField(blank=True, default='', max_length=255, verbose_name='Email')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('family_id', models.BigIntegerField(blank=True, null=True, verbose_name='Family ID')),
                ('section', models.CharField(blank=True, default='', max_length=100, verbose_name='牧區')),
                ('family1', models.CharField(blank=True, default='', max_length=255, verbose_name='小組')),
                ('dataindate', models.DateField(blank=True, null=True, verbose_name='資料輸入日期')),
                ('att_y', models.CharField(blank=True, default='', max_length=255, verbose_name='出席總覽年份/代碼')),
                ('att_12m', models.IntegerField(blank=True, null=True, verbose_name='近12個月出席')),
                ('att_str', models.TextField(blank=True, default='', verbose_name='出席詳情')),
                ('percent_year', models.CharField(blank=True, default='', max_length=255, verbose_name='年度出席率')),
                ('data_str', models.TextField(blank=True, default='', verbose_name='出席詳情圖')),
                ('percent_12_month', models.CharField(blank=True, default='', max_length=255, verbose_name='近12月出席率')),
                ('first_daka', models.CharField(blank=True, default='', max_length=50, verbose_name='首次打卡')),
                ('gender', models.CharField(blank=True, default='', max_length=10, verbose_name='性別')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('join_date', models.DateField(blank=True, null=True, verbose_name='加入日期')),
                ('baptized', models.CharField(blank=True, default='', max_length=10, verbose_name='已洗禮')),
                ('presence', models.IntegerField(default=0, verbose_name='在場/現況')),
                ('marriage', models.CharField(blank=True, default='', max_length=50, verbose_name='婚姻狀況')),
                ('phone_h', models.CharField(blank=True, default='', max_length=50, verbose_name='住家電話')),
                ('phone_o', models.CharField(blank=True, default='', max_length=50, verbose_name='辦公電話')),
                ('visitor_info', models.CharField(blank=True, default='', max_length=255, verbose_name='訪客資訊')),
                ('car_number', models.CharField(blank=True, default='', max_length=50, verbose_name='車牌號碼')),
                ('line_id', models.CharField(blank=True, default='', max_length=100, verbose_name='Line ID')),
                ('photo_base64', models.TextField(blank=True, default='', verbose_name='照片 Base64')),
            ],
            options={
                'verbose_name': '人員',
                'verbose_name_plural': '人員',
                'db_table': 'members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=50, verbose_name='員工編號')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('card_no', models.CharField(blank=True, default='', max_length=50, verbose_name='卡號')),
                ('timestamp', models.DateTimeField(verbose_name='打卡時間')),
                ('serial_no', models.IntegerField(unique=True, verbose_name='設備流水號')),
            ],
            options={
                'verbose_name': '員工打卡記錄',
                'verbose_name_plural': '員工打卡記錄',
                'db_table': 'staff_attendance',
                'ordering': ['-timestamp'],
            },
        ),
    ]
