# Generated by Django 5.2.14 on 2026-06-10 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDutyNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='日期')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='行政備註')),
            ],
            options={
                'verbose_name': '每日行政備註',
                'verbose_name_plural': '每日行政備註',
                'db_table': 'daily_duty_notes',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StaffLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100, verbose_name='同工姓名')),
                ('date', models.DateField(verbose_name='日期')),
                ('time_slot', models.CharField(choices=[('AM', '上午'), ('PM', '下午')], max_length=10, verbose_name='時段')),
                ('leave_type', models.CharField(blank=True, default='', max_length=50, verbose_name='假別')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves', to='eureka.member')),
            ],
            options={
                'verbose_name': '同工休假記錄',
                'verbose_name_plural': '同工休假記錄',
                'db_table': 'staff_leaves',
                'ordering': ['-date', 'staff_name', 'time_slot'],
                'unique_together': {('staff_name', 'date', 'time_slot')},
            },
        ),
    ]
