# Generated by Django 5.2.14 on 2026-06-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0002_dailydutynote_staffleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('staff_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='同工編號')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('identity_code', models.CharField(blank=True, default='', max_length=50, verbose_name='身分代碼')),
                ('is_active', models.BooleanField(default=True, verbose_name='在職狀態')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='本人Email')),
                ('cc_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='CC Email')),
                ('onboard_date', models.DateField(blank=True, null=True, verbose_name='到職日期')),
                ('leave_quotas', models.JSONField(blank=True, default=dict, verbose_name='歷年休假額度')),
            ],
            options={
                'verbose_name': '同工資料',
                'verbose_name_plural': '同工資料',
                'db_table': 'staff_info',
                'ordering': ['staff_id'],
            },
        ),
    ]
