# Generated by Django 5.2.14 on 2026-06-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0003_staffinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinfo',
            name='annual_leave_quota',
            field=models.FloatField(default=0.0, verbose_name='年度特休'),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='employee_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='工號'),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='locker_no',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='櫃號'),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='手機號碼'),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='seat',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='座位'),
        ),
    ]
