# Generated by Django 5.2.14 on 2026-06-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0004_staffinfo_annual_leave_quota_staffinfo_employee_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='預設座位圖', max_length=100, verbose_name='配置名稱')),
                ('layout_data', models.JSONField(blank=True, default=dict, verbose_name='配置JSON資料')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '座位配置圖',
                'verbose_name_plural': '座位配置圖',
                'db_table': 'seat_maps',
            },
        ),
    ]
