# Generated by Django 5.2.14 on 2026-06-30 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0005_seatmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffinfo',
            name='bank_account',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='????'),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='??(??)'),
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_infos', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
