# Generated by Django 5.2.14 on 2026-07-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0006_staffinfo_bank_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerMeetingAttendance',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='週(週四日期)')),
                ('attendance', models.IntegerField(default=0, verbose_name='人數')),
            ],
            options={
                'verbose_name': '禱告會人數',
                'verbose_name_plural': '禱告會人數',
                'db_table': 'prayer_meeting_attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeeklyAttendance',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='週(主日日期)')),
                ('first_service', models.IntegerField(blank=True, null=True, verbose_name='第一堂')),
                ('second_service', models.IntegerField(blank=True, null=True, verbose_name='第二堂')),
                ('evening_service', models.IntegerField(blank=True, null=True, verbose_name='晚堂')),
                ('online', models.IntegerField(blank=True, null=True, verbose_name='線上')),
                ('children', models.IntegerField(blank=True, null=True, verbose_name='兒主')),
                ('youth', models.IntegerField(blank=True, null=True, verbose_name='青少')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='總計')),
                ('new_friends', models.IntegerField(blank=True, null=True, verbose_name='主日新朋友')),
                ('remark', models.TextField(blank=True, default='', verbose_name='註記(不含新朋友)')),
            ],
            options={
                'verbose_name': '每週聚會人數',
                'verbose_name_plural': '每週聚會人數',
                'db_table': 'weekly_attendance',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='YearlyAttendance',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False, verbose_name='年')),
                ('attendance', models.IntegerField(default=0, verbose_name='聚會人數')),
                ('baptized', models.IntegerField(default=0, verbose_name='受洗')),
                ('remark', models.TextField(blank=True, default='', verbose_name='備註')),
            ],
            options={
                'verbose_name': '歷年人數統計',
                'verbose_name_plural': '歷年人數統計',
                'db_table': 'yearly_attendance',
                'ordering': ['year'],
            },
        ),
    ]
