# Generated by Django 5.2.16 on 2026-07-26 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0007_prayermeetingattendance_weeklyattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_code', models.CharField(max_length=50, unique=True, verbose_name='班表代號')),
                ('description', models.CharField(blank=True, default='', max_length=100, verbose_name='班表名稱/描述')),
                ('mon_start', models.TimeField(blank=True, null=True, verbose_name='週一上班時間')),
                ('mon_end', models.TimeField(blank=True, null=True, verbose_name='週一下班時間')),
                ('tue_start', models.TimeField(blank=True, null=True, verbose_name='週二上班時間')),
                ('tue_end', models.TimeField(blank=True, null=True, verbose_name='週二下班時間')),
                ('wed_start', models.TimeField(blank=True, null=True, verbose_name='週三上班時間')),
                ('wed_end', models.TimeField(blank=True, null=True, verbose_name='週三下班時間')),
                ('thu_start', models.TimeField(blank=True, null=True, verbose_name='週四上班時間')),
                ('thu_end', models.TimeField(blank=True, null=True, verbose_name='週四下班時間')),
                ('fri_start', models.TimeField(blank=True, null=True, verbose_name='週五上班時間')),
                ('fri_end', models.TimeField(blank=True, null=True, verbose_name='週五下班時間')),
                ('sat_start', models.TimeField(blank=True, null=True, verbose_name='週六上班時間')),
                ('sat_end', models.TimeField(blank=True, null=True, verbose_name='週六下班時間')),
                ('sun_start', models.TimeField(blank=True, null=True, verbose_name='週日上班時間')),
                ('sun_end', models.TimeField(blank=True, null=True, verbose_name='週日下班時間')),
            ],
            options={
                'verbose_name': '同工班表',
                'verbose_name_plural': '同工班表',
                'db_table': 'staff_shifts',
            },
        ),
        migrations.AddField(
            model_name='staffinfo',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_infos', to='eureka.staffshift', verbose_name='班表'),
        ),
    ]
