# Generated by Django 5.2.16 on 2026-07-30 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eureka', '0008_staffshift_staffinfo_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralOverseer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='區牧名字')),
            ],
            options={
                'verbose_name': '區牧',
                'verbose_name_plural': '區牧',
                'db_table': 'pastoral_overseers',
            },
        ),
        migrations.CreateModel(
            name='PastoralSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='牧區名稱')),
                ('counselor', models.CharField(blank=True, default='', max_length=255, verbose_name='輔導')),
                ('leader', models.CharField(blank=True, default='', max_length=255, verbose_name='區長')),
                ('overseer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='eureka.pastoraloverseer')),
            ],
            options={
                'verbose_name': '牧區',
                'verbose_name_plural': '牧區',
                'db_table': 'pastoral_sections',
            },
        ),
        migrations.CreateModel(
            name='PastoralGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='小組名稱')),
                ('meeting_time', models.CharField(blank=True, default='', max_length=255, verbose_name='聚會時間')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='地點')),
                ('target', models.CharField(blank=True, default='', max_length=255, verbose_name='對象')),
                ('topic', models.CharField(blank=True, default='', max_length=255, verbose_name='近期聚會主題')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='小組照片')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='eureka.pastoralsection')),
            ],
            options={
                'verbose_name': '小組',
                'verbose_name_plural': '小組',
                'db_table': 'pastoral_groups',
            },
        ),
    ]
