# Generated by Django 5.2.14 on 2026-05-16 00:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_ename', models.CharField(blank=True, default='', max_length=50, verbose_name='同工英文名')),
                ('display_name', models.CharField(blank=True, default='', max_length=100, verbose_name='顯示名稱（中文姓名）')),
                ('department', models.CharField(blank=True, default='', max_length=50, verbose_name='部門')),
                ('worker_id', models.CharField(blank=True, default='', max_length=20, verbose_name='同工編號')),
                ('role', models.CharField(blank=True, default='', max_length=50, verbose_name='角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '使用者擴充資料',
                'verbose_name_plural': '使用者擴充資料',
            },
        ),
    ]
