# Generated by Django 5.2.14 on 2026-05-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='系統內部識別碼，請勿修改。', max_length=50, unique=True, verbose_name='設定鍵')),
                ('value', models.TextField(blank=True, verbose_name='設定值')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '系統設定',
                'verbose_name_plural': '系統設定',
            },
        ),
    ]
