# Generated by Django 5.2.14 on 2026-05-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemsetting'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_menu_items',
            field=models.ManyToManyField(blank=True, to='menu.menuitem', verbose_name='可存取的選單項目'),
        ),
    ]
