# Generated by Django 5.2.16 on 2026-08-12 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_path', models.CharField(default='/app/backups', max_length=500, verbose_name='備份路徑')),
                ('dest_type', models.CharField(choices=[('local', '本機目錄'), ('sftp', 'SFTP (遠端主機/NAS)')], default='local', max_length=20, verbose_name='備份目的地類型')),
                ('sftp_host', models.CharField(blank=True, default='', max_length=255, verbose_name='遠端主機/NAS IP')),
                ('sftp_port', models.IntegerField(default=22, verbose_name='遠端主機 Port')),
                ('sftp_username', models.CharField(blank=True, default='', max_length=100, verbose_name='遠端使用者名稱')),
                ('sftp_password', models.CharField(blank=True, default='', max_length=255, verbose_name='遠端密碼')),
                ('schedule_enabled', models.BooleanField(default=False, verbose_name='啟用定期備份')),
                ('backup_time', models.TimeField(default=datetime.time(2, 0), verbose_name='備份時間')),
                ('retention_type', models.CharField(choices=[('count', '保留最新份數'), ('days', '保留天數')], default='count', max_length=20, verbose_name='保留規則')),
                ('retention_value', models.IntegerField(default=10, verbose_name='保留數量/天數')),
            ],
            options={
                'verbose_name': '備份設定',
                'verbose_name_plural': '備份設定',
            },
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='備份檔名')),
                ('filepath', models.CharField(max_length=500, verbose_name='備份路徑')),
                ('filesize', models.BigIntegerField(default=0, verbose_name='檔案大小 (Bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='備份時間')),
                ('status', models.CharField(choices=[('pending', '備份中'), ('success', '成功'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='備份狀態')),
                ('log', models.TextField(blank=True, default='', verbose_name='備份記錄/過程')),
                ('comment', models.TextField(blank=True, default='', verbose_name='備份註解')),
                ('trigger_type', models.CharField(choices=[('manual', '手動'), ('scheduled', '排程')], default='manual', max_length=20, verbose_name='觸發類型')),
            ],
            options={
                'verbose_name': '備份紀錄',
                'verbose_name_plural': '備份紀錄',
                'ordering': ['-created_at'],
            },
        ),
    ]
