# Generated by Django 5.2.16 on 2026-07-28 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicMaintenanceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='分類')),
                ('name', models.CharField(max_length=200, verbose_name='設施名稱/維護項目')),
                ('cycle', models.CharField(blank=True, default='', max_length=100, verbose_name='維護週期')),
                ('description', models.TextField(blank=True, default='', verbose_name='說明')),
                ('owner', models.CharField(blank=True, default='', max_length=100, verbose_name='主責同工')),
                ('vendor', models.CharField(blank=True, default='', max_length=100, verbose_name='外包廠商')),
                ('scheduled_weeks', models.TextField(default='[]', help_text='例如: [1, 13, 26, 39]', verbose_name='需維護週次(JSON)')),
                ('order_num', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用狀態')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '定期維護項目',
                'verbose_name_plural': '定期維護項目',
                'ordering': ['order_num', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodicMaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('week_number', models.IntegerField(verbose_name='週次')),
                ('status', models.CharField(default='completed', max_length=20, verbose_name='狀態')),
                ('anomaly_note', models.TextField(blank=True, default='', verbose_name='異常說明/備註')),
                ('operator_name', models.CharField(blank=True, default='', max_length=100, verbose_name='操作人員')),
                ('ip_address', models.CharField(blank=True, default='', max_length=50, verbose_name='IP位置')),
                ('mac_address', models.CharField(blank=True, default='', max_length=255, verbose_name='MAC/裝置資訊')),
                ('gps_location', models.CharField(blank=True, default='', max_length=100, verbose_name='GPS座標')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完成時間')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='facility.periodicmaintenanceitem', verbose_name='維護項目')),
            ],
            options={
                'verbose_name': '定期維護紀錄',
                'verbose_name_plural': '定期維護紀錄',
                'ordering': ['-year', '-week_number', 'id'],
                'unique_together': {('item', 'year', 'week_number')},
            },
        ),
    ]
