# Generated by Django 5.2.16 on 2026-07-28 16:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodicmaintenancerecord',
            name='device_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='設備名稱'),
        ),
        migrations.AddField(
            model_name='periodicmaintenancerecord',
            name='maintenance_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='維護日期'),
        ),
        migrations.AddField(
            model_name='periodicmaintenancerecord',
            name='ssid',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='SSID/網路名稱'),
        ),
        migrations.AlterField(
            model_name='periodicmaintenancerecord',
            name='anomaly_note',
            field=models.TextField(blank=True, default='', verbose_name='狀況說明/備註'),
        ),
        migrations.AlterField(
            model_name='periodicmaintenancerecord',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='登記時間'),
        ),
        migrations.AlterField(
            model_name='periodicmaintenancerecord',
            name='mac_address',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='MAC位置'),
        ),
        migrations.AlterField(
            model_name='periodicmaintenancerecord',
            name='operator_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='登記人員'),
        ),
    ]
