# Generated by Django 5.2.14 on 2026-05-16 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='標題')),
                ('route', models.CharField(blank=True, default='', help_text='連結路徑，例如 /expense。父目錄留空即可。', max_length=200, verbose_name='路由')),
                ('icon', models.CharField(blank=True, default='', help_text='選填，例如 🎇 或 Material Icon 名稱', max_length=50, verbose_name='圖示')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='數字越小越前面', verbose_name='排序')),
                ('roles', models.CharField(default='*', help_text='逗號分隔角色名稱，* 表示所有人可見。例如：admin,staff', max_length=200, verbose_name='可見角色')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem', verbose_name='上層目錄')),
            ],
            options={
                'verbose_name': '選單項目',
                'verbose_name_plural': '選單項目',
                'ordering': ['order', 'id'],
            },
        ),
    ]
