# Generated by Hand to add new worship/liturgy menu items

from django.db import migrations

def add_liturgy_menu_items(apps, schema_editor):
    MenuItem = apps.get_model('menu', 'MenuItem')
    try:
        parent = MenuItem.objects.get(title='崇拜禮儀')
    except MenuItem.DoesNotExist:
        # If parent doesn't exist, create it as a root menu
        parent = MenuItem.objects.create(
            title='崇拜禮儀',
            route='',
            icon='',
            order=10,
            roles='*',
            is_active=True
        )
    
    items_to_add = [
        {'title': '洗禮', 'route': '/worship/baptism/', 'order': 2},
        {'title': '聖餐禮', 'route': '/worship/communion/', 'order': 3},
        {'title': '婚禮', 'route': '/worship/wedding/', 'order': 4},
        {'title': '安息禮拜', 'route': '/worship/funeral/', 'order': 5},
    ]
    
    for item in items_to_add:
        MenuItem.objects.get_or_create(
            title=item['title'],
            parent=parent,
            defaults={
                'route': item['route'],
                'order': item['order'],
                'roles': '*',
                'is_active': True
            }
        )

def remove_liturgy_menu_items(apps, schema_editor):
    MenuItem = apps.get_model('menu', 'MenuItem')
    MenuItem.objects.filter(
        title__in=['洗禮', '聖餐禮', '婚禮', '安息禮拜'],
        parent__title='崇拜禮儀'
    ).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_liturgy_menu_items, remove_liturgy_menu_items),
    ]
