# Generated by Hand to add new Education & Course Planning menu items

from django.db import migrations

def add_education_menu_items(apps, schema_editor):
    MenuItem = apps.get_model('menu', 'MenuItem')
    
    # 1. Create root menu '教育'
    education_parent, _ = MenuItem.objects.get_or_create(
        title='教育',
        parent=None,
        defaults={
            'route': '',
            'icon': '🎓',
            'order': 50,
            'roles': '*',
            'is_active': True
        }
    )
    
    # 2. Create sub-menu item '課程規劃' under '教育'
    MenuItem.objects.get_or_create(
        title='課程規劃',
        parent=education_parent,
        defaults={
            'route': '/education/courses/',
            'order': 1,
            'roles': '*',
            'is_active': True
        }
    )

def remove_education_menu_items(apps, schema_editor):
    MenuItem = apps.get_model('menu', 'MenuItem')
    # Delete sub-menu item '課程規劃'
    MenuItem.objects.filter(route='/education/courses/').delete()
    # Delete root menu '教育'
    MenuItem.objects.filter(title='教育', parent=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_adjust_menu_items_pastoral_deacons'),
    ]

    operations = [
        migrations.RunPython(add_education_menu_items, remove_education_menu_items),
    ]
