# Generated by Django 5.2.16 on 2026-08-04 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text='自動產生，例如: RS2026001', max_length=20, unique=True, verbose_name='課程代號')),
                ('subject', models.CharField(max_length=255, verbose_name='課程主題')),
                ('introduction', models.TextField(blank=True, default='', verbose_name='簡介')),
                ('teachers', models.CharField(help_text='多位老師可用逗號分隔', max_length=255, verbose_name='師資')),
                ('class_leader', models.CharField(blank=True, default='', max_length=255, verbose_name='班長')),
                ('total_classes', models.PositiveIntegerField(default=1, verbose_name='課程次數')),
                ('hours_per_class', models.PositiveIntegerField(default=60, verbose_name='每次上課時數(分鐘)')),
                ('class_time', models.CharField(help_text='例如: 每週六早上 09:00 - 11:00', max_length=255, verbose_name='上課時間')),
                ('makeup_required', models.BooleanField(default=False, verbose_name='是否補課？')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '課程規劃',
                'verbose_name_plural': '課程規劃',
                'ordering': ['-code'],
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_number', models.PositiveIntegerField(help_text='第幾堂課', verbose_name='堂次')),
                ('date', models.DateField(blank=True, null=True, verbose_name='上課日期')),
                ('subject', models.CharField(blank=True, default='', max_length=255, verbose_name='課堂主題')),
                ('teacher', models.CharField(blank=True, default='', max_length=255, verbose_name='授課老師')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='education.course', verbose_name='課程')),
            ],
            options={
                'verbose_name': '課程表單堂',
                'verbose_name_plural': '課程表單堂',
                'ordering': ['class_number'],
            },
        ),
    ]
