# Generated by Django 5.2.16 on 2026-08-04 04:25

import django.core.files.storage
import django.db.models.deletion
import pathlib
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseClassRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/app/private_media')), upload_to='education/recordings/', verbose_name='錄音檔案')),
                ('filename', models.CharField(max_length=255, verbose_name='原始檔名')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='檔案大小(Bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上傳時間')),
                ('course_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='education.courseclass', verbose_name='課堂')),
            ],
            options={
                'verbose_name': '課堂錄音',
                'verbose_name_plural': '課堂錄音',
            },
        ),
        migrations.CreateModel(
            name='CoursePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='標題')),
                ('content', models.TextField(verbose_name='內容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='發佈時間')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='education.course')),
            ],
            options={
                'verbose_name': '課程討論版公告',
                'verbose_name_plural': '課程討論版公告',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MakeUpRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='完成登記時間')),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_records', to='education.courseclass', verbose_name='課堂')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_records', to=settings.AUTH_USER_MODEL, verbose_name='學員')),
            ],
            options={
                'verbose_name': '學員補課紀錄',
                'verbose_name_plural': '學員補課紀錄',
                'unique_together': {('user', 'course_class')},
            },
        ),
    ]
