# Generated by Django 5.2.16 on 2026-08-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_courseclassrecording_coursepost_makeuprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='classroom_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='教室ID'),
        ),
        migrations.AddField(
            model_name='course',
            name='classroom_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='教室名稱'),
        ),
    ]
