# Generated by Django 5.2.11 on 2026-02-24 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HymnCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分類名稱')),
                ('description', models.TextField(blank=True, default='', verbose_name='說明')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '詩歌分類',
                'verbose_name_plural': '詩歌分類',
                'db_table': 'hymn_category',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(db_index=True, help_text='詩歌編號，例如 1, 2, 3...', unique=True, verbose_name='編號')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='曲名')),
                ('title_en', models.CharField(blank=True, default='', max_length=200, verbose_name='英文曲名')),
                ('author', models.CharField(blank=True, default='', max_length=200, verbose_name='作詞者')),
                ('composer', models.CharField(blank=True, default='', max_length=200, verbose_name='作曲者')),
                ('key_signature', models.CharField(blank=True, default='', help_text='例如: C, Dm, G', max_length=20, verbose_name='調性')),
                ('time_signature', models.CharField(blank=True, default='', help_text='例如: 4/4, 3/4, 6/8', max_length=10, verbose_name='拍號')),
                ('lyrics', models.TextField(blank=True, default='', help_text='純文字歌詞', verbose_name='歌詞')),
                ('pdf_file', models.FileField(blank=True, default='', upload_to='hymns/pdf/', verbose_name='五線譜 PDF')),
                ('midi_file', models.FileField(blank=True, default='', upload_to='hymns/midi/', verbose_name='MIDI 檔')),
                ('mp3_file', models.FileField(blank=True, default='', upload_to='hymns/mp3/', verbose_name='MP3 檔')),
                ('html_score', models.FileField(blank=True, default='', help_text='HTML 格式的樂譜檔案', upload_to='hymns/html/', verbose_name='HTML 樂譜')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hymns', to='hymns.hymncategory', verbose_name='分類')),
            ],
            options={
                'verbose_name': '詩歌',
                'verbose_name_plural': '詩歌',
                'db_table': 'hymn',
                'ordering': ['number'],
            },
        ),
    ]
