# Generated by Django 5.2.14 on 2026-05-28 04:53

from django.db import migrations


def drop_hymn_table(apps, schema_editor):
    if schema_editor.connection.vendor == 'sqlite':
        pass
    else:
        schema_editor.execute("SET FOREIGN_KEY_CHECKS = 0;")
        schema_editor.execute("DROP TABLE IF EXISTS hymn;")
        schema_editor.execute("SET FOREIGN_KEY_CHECKS = 1;")


class Migration(migrations.Migration):

    dependencies = [
        ('hymns', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            drop_hymn_table,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='hymn',
            name='category',
        ),
        migrations.DeleteModel(
            name='HymnCategory',
        ),
        migrations.AlterModelOptions(
            name='hymn',
            options={'managed': False, 'ordering': ['id'], 'verbose_name': '詩歌', 'verbose_name_plural': '詩歌'},
        ),
    ]


