# Generated by Django 5.2.14 on 2026-07-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hymns', '0002_delete_hymncategory_alter_hymn_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hymn',
            table='hymns',
        ),
    ]
