# Generated by Django 5.2.14 on 2026-06-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPowerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(blank=True, max_length=20, null=True)),
                ('usage_date', models.DateField(blank=True, null=True)),
                ('total_usage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('peak_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '每日用電報告',
                'verbose_name_plural': '每日用電報告',
                'db_table': 'daily_power_report',
                'ordering': ['usage_date'],
                'managed': True,
            },
        ),
    ]
