# Generated by Django 5.2.14 on 2026-05-16 09:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='標題')),
                ('slug', models.SlugField(help_text='例如：home, contact', max_length=200, unique=True, verbose_name='網址路徑')),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', verbose_name='網頁內容')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '網頁內容',
                'verbose_name_plural': '網頁內容',
            },
        ),
    ]
