# Generated by Django 5.2.14 on 2026-05-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='檔名')),
                ('path', models.TextField(verbose_name='路徑')),
                ('duration', models.CharField(default='未知', max_length=50, verbose_name='時長')),
                ('file_type', models.CharField(default='', max_length=10, verbose_name='類型')),
                ('size', models.BigIntegerField(default=0, verbose_name='檔案大小')),
                ('last_scanned', models.DateTimeField(auto_now=True, verbose_name='掃描時間')),
            ],
            options={
                'verbose_name': '影音收藏',
                'verbose_name_plural': '影音收藏',
            },
        ),
    ]
