# Generated by Django 5.2.16 on 2026-07-28 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_mediacollection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaptismSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='洗禮日期')),
                ('location', models.CharField(max_length=200, verbose_name='洗禮場次/地點')),
                ('pastor', models.CharField(max_length=100, verbose_name='主領牧師')),
            ],
            options={
                'verbose_name': '洗禮場次',
                'verbose_name_plural': '洗禮場次',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BaptismPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='洗禮日期')),
                ('pastor', models.CharField(max_length=100, verbose_name='主禮牧師')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('gender', models.CharField(max_length=10, verbose_name='性別')),
                ('category', models.CharField(max_length=50, verbose_name='洗禮類別')),
                ('note', models.TextField(blank=True, default='', verbose_name='註記')),
                ('interview_pastor', models.CharField(blank=True, default='', max_length=100, verbose_name='受洗約談牧者')),
                ('gift_bible', models.CharField(blank=True, default='', max_length=100, verbose_name='贈送聖經')),
                ('verse', models.CharField(blank=True, default='', max_length=255, verbose_name='受洗經文')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='pages.baptismsession', verbose_name='洗禮場次')),
            ],
            options={
                'verbose_name': '受洗者',
                'verbose_name_plural': '受洗者',
                'ordering': ['-date', 'id'],
            },
        ),
    ]
