# Generated by Django 5.2.16 on 2026-07-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_baptismsession_baptismperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='baptismperson',
            name='is_completed',
            field=models.BooleanField(default=True, verbose_name='受洗完成'),
        ),
    ]
