# Generated by Django 5.2.16 on 2026-07-28 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_baptismperson_is_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=100, verbose_name='故人姓名')),
                ('deceased_date_of_birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('deceased_date_of_death', models.DateField(blank=True, null=True, verbose_name='安息日期')),
                ('deceased_age', models.IntegerField(blank=True, null=True, verbose_name='安息年齡')),
                ('family_contact', models.CharField(blank=True, default='', max_length=100, verbose_name='家屬聯絡人')),
                ('family_relationship', models.CharField(blank=True, default='', max_length=50, verbose_name='關係')),
                ('family_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='聯絡電話')),
                ('service_date', models.DateField(verbose_name='禮拜日期')),
                ('service_time', models.CharField(blank=True, default='', max_length=50, verbose_name='禮拜時間')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='禮拜地點')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註/備忘錄')),
                ('pastor', models.CharField(blank=True, default='', max_length=100, verbose_name='主禮牧師')),
                ('preacher', models.CharField(blank=True, default='', max_length=100, verbose_name='證道人員')),
                ('leader', models.CharField(blank=True, default='', max_length=100, verbose_name='司會人員')),
                ('pianist', models.CharField(blank=True, default='', max_length=100, verbose_name='司琴人員')),
                ('sound', models.CharField(blank=True, default='', max_length=100, verbose_name='司音/音控')),
                ('projection', models.CharField(blank=True, default='', max_length=100, verbose_name='投影/簡報')),
                ('ushers', models.CharField(blank=True, default='', max_length=255, verbose_name='招待人員')),
                ('choir', models.CharField(blank=True, default='', max_length=255, verbose_name='獻詩/詩班')),
                ('traffic', models.CharField(blank=True, default='', max_length=255, verbose_name='交通指引')),
                ('is_completed', models.BooleanField(default=False, verbose_name='禮拜已完成')),
            ],
            options={
                'verbose_name': '安息禮拜',
                'verbose_name_plural': '安息禮拜',
                'ordering': ['-service_date', 'id'],
            },
        ),
    ]
