# Generated by Django 5.2.16 on 2026-07-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_funeralservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='funeralservice',
            name='burial',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='安厝人員'),
        ),
        migrations.AddField(
            model_name='funeralservice',
            name='coffining',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='入殮人員'),
        ),
        migrations.AddField(
            model_name='funeralservice',
            name='cremation',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='火化人員'),
        ),
        migrations.AddField(
            model_name='funeralservice',
            name='prayer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='禱告人員'),
        ),
        migrations.AddField(
            model_name='funeralservice',
            name='scripture',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='讀經人員'),
        ),
    ]
