# Generated by Django 5.2.16 on 2026-07-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_funeralservice_burial_funeralservice_coffining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.IntegerField(unique=True, verbose_name='組別')),
                ('preacher', models.CharField(blank=True, default='', max_length=100, verbose_name='講道(主理)')),
                ('leader', models.CharField(blank=True, default='', max_length=100, verbose_name='司會')),
                ('scripture_prayer', models.CharField(blank=True, default='', max_length=100, verbose_name='讀經+禱告')),
            ],
            options={
                'verbose_name': '安息服事班表',
                'verbose_name_plural': '安息服事班表',
                'ordering': ['group_no'],
            },
        ),
    ]
