# Generated by Django 5.2.16 on 2026-08-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_funeralshift'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeaconBoardMinutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='會議名稱')),
                ('meeting_date', models.DateField(verbose_name='會議日期')),
                ('summary', models.TextField(blank=True, default='', verbose_name='會議摘要')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='board_minutes/', verbose_name='會議紀錄檔案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
            ],
            options={
                'verbose_name': '執事會會議紀錄',
                'verbose_name_plural': '執事會會議紀錄',
                'ordering': ['-meeting_date', '-id'],
            },
        ),
    ]
