# Generated by Django 5.2.16 on 2026-07-28 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('download', '下載'), ('upload', '上傳')], max_length=20, verbose_name='操作類型')),
                ('path', models.CharField(max_length=500, verbose_name='相對路徑')),
                ('ip_address', models.CharField(blank=True, default='', max_length=50, verbose_name='IP 位址')),
                ('mac_address', models.CharField(blank=True, default='', max_length=50, verbose_name='MAC 位址')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='經度')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='記錄時間')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '檔案操作紀錄',
                'verbose_name_plural': '檔案操作紀錄',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FileAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='相對於檔案中心根目錄的相對路徑', max_length=500, unique=True, verbose_name='相對路徑')),
                ('is_directory', models.BooleanField(default=False, verbose_name='是否為目錄')),
                ('notes', models.TextField(blank=True, default='', verbose_name='註記內容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': '檔案註記',
                'verbose_name_plural': '檔案註記',
            },
        ),
    ]
