from django.urls import path, re_path
from . import views

urlpatterns = [
    path('planned/', views.planned_page, name='planned-feature'),
    path('booking/day/', views.booking_daily_overview, name='facility-booking-day'),
    path('booking/', views.booking_page, name='facility-booking'),
    path('rooms/', views.room_admin_page, name='facility-rooms'),
    path('maintenance/', views.maintenance_page, name='facility-maintenance'),
    path('booking/export/', views.export_bookings, name='facility-booking-export'),
    path('expense-claims/', views.expense_claim_page, name='facility-expense-claims'),
    path('expense-claims/<str:claim_no>/voucher.pdf', views.expense_claim_voucher_pdf, name='facility-expense-claim-voucher'),
    path('pastoral-reports/', views.pastoral_report_page, name='facility-pastoral-reports'),
    path('pastoral-reports/admin/', views.pastoral_report_admin_page, name='facility-pastoral-report-admin'),
    path('pastoral-reports/<str:report_no>/report.pdf', views.pastoral_report_pdf, name='facility-pastoral-report-pdf'),
    path('lan-hosts/', views.network_lan_hosts_page, name='facility-network-lan-hosts'),
    path('lan-hosts/scan/', views.network_lan_hosts_scan, name='facility-network-lan-hosts-scan'),
    path('lan-hosts/note/', views.network_lan_hosts_note, name='facility-network-lan-hosts-note'),
    path('lan-hosts/ping/', views.network_lan_hosts_ping, name='facility-network-lan-hosts-ping'),
    path('wlan-aps/', views.network_wlan_aps_page, name='facility-network-wlan-aps'),
    path('wlan-aps/scan/', views.network_wlan_aps_scan, name='facility-network-wlan-aps-scan'),
    path('classroom-inspection/', views.classroom_inspection_page, name='facility-classroom-inspection'),
    path('classroom-inspection/room/<int:room_id>/inspect/', views.classroom_mobile_inspect_page, name='facility-classroom-mobile-inspect'),
    path('classroom-inspection/room/<int:room_id>/qrcode/', views.classroom_qrcode_image, name='facility-classroom-qrcode'),
    path('classroom-inspection/api/rooms/', views.classroom_inspection_api_rooms, name='facility-classroom-api-rooms'),
    path('classroom-inspection/api/items/', views.classroom_inspection_api_items, name='facility-classroom-api-items'),
    path('classroom-inspection/export-pdf/', views.classroom_inspection_pdf, name='facility-classroom-inspection-pdf'),
    path('periodic-maintenance/', views.periodic_maintenance_page, name='facility-periodic-maintenance'),
    path('periodic-maintenance/report/', views.periodic_maintenance_report_page, name='facility-periodic-maintenance-report'),
    path('periodic-maintenance/report/<int:item_id>/', views.periodic_maintenance_report_page, name='facility-periodic-maintenance-report-item'),
    path('periodic-maintenance/item/<int:item_id>/qrcode/', views.periodic_maintenance_qrcode_image, name='facility-periodic-maintenance-qrcode'),
    path('periodic-maintenance/api/items/', views.periodic_maintenance_api_items, name='facility-periodic-maintenance-api-items'),
    path('periodic-maintenance/api/records/', views.periodic_maintenance_api_records, name='facility-periodic-maintenance-api-records'),
    re_path(r'^(?P<unused_path>.+)/?$', views.planned_page, name='facility-planned-catchall'),
]
