# Generated by Django 5.2.14 on 2026-07-09 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_usage_and_change_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='帳戶類別')),
                ('bank', models.CharField(blank=True, default='', max_length=100, verbose_name='銀行')),
                ('account_no', models.CharField(blank=True, default='', max_length=100, verbose_name='帳號')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '銀行帳戶',
                'verbose_name_plural': '銀行帳戶',
                'db_table': 'bank_accounts',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TimeDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='帳戶類別')),
                ('duration', models.CharField(blank=True, default='', max_length=100, verbose_name='存單期間')),
                ('period', models.CharField(blank=True, default='', max_length=50, verbose_name='期別')),
                ('deposit_type', models.CharField(blank=True, default='', max_length=50, verbose_name='存單類別')),
                ('deposit_no', models.CharField(blank=True, default='', max_length=100, verbose_name='存單編號')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=8, null=True, verbose_name='利率%')),
                ('rate_type', models.CharField(blank=True, default='', max_length=20, verbose_name='固定/機動')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='金額')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '定期存單',
                'verbose_name_plural': '定期存單',
                'db_table': 'time_deposits',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, verbose_name='月份')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='餘額')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='budget.bankaccount', verbose_name='銀行帳戶')),
            ],
            options={
                'verbose_name': '帳戶餘額',
                'verbose_name_plural': '帳戶餘額',
                'db_table': 'account_balances',
                'ordering': ['-month', 'account__order'],
                'constraints': [models.UniqueConstraint(fields=('account', 'month'), name='unique_account_month')],
            },
        ),
    ]
