# Generated by Django 5.2.14 on 2026-07-09 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_bankaccount_timedeposit_accountbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='團契名稱')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '團契',
                'verbose_name_plural': '團契',
                'db_table': 'fellowships',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='基金名稱')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否啟用')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '基金',
                'verbose_name_plural': '基金',
                'db_table': 'funds',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FellowshipBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, verbose_name='月份')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='餘額')),
                ('fellowship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='budget.fellowship', verbose_name='團契')),
            ],
            options={
                'verbose_name': '團契餘額',
                'verbose_name_plural': '團契餘額',
                'db_table': 'fellowship_balances',
                'ordering': ['-month', 'fellowship__order'],
                'constraints': [models.UniqueConstraint(fields=('fellowship', 'month'), name='unique_fellowship_month')],
            },
        ),
        migrations.CreateModel(
            name='FundBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, verbose_name='月份')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='餘額')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='budget.fund', verbose_name='基金')),
            ],
            options={
                'verbose_name': '基金餘額',
                'verbose_name_plural': '基金餘額',
                'db_table': 'fund_balances',
                'ordering': ['-month', 'fund__order'],
                'constraints': [models.UniqueConstraint(fields=('fund', 'month'), name='unique_fund_month')],
            },
        ),
    ]
