# Generated by Django 5.2.14 on 2026-07-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_fellowship_fund_fellowshipbalance_fundbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, unique=True, verbose_name='年度')),
                ('pledge_people_count', models.IntegerField(blank=True, null=True, verbose_name='月定人數')),
                ('sunday', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='主日奉獻')),
                ('pledge', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='月定奉獻')),
                ('thanksgiving', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='感恩奉獻')),
                ('building', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='建築奉獻')),
                ('planting', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='植堂奉獻')),
                ('designated', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='指定奉獻')),
                ('mission', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='宣教&大陸奉獻')),
                ('galilee', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='加利利基金')),
                ('timothy', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='提摩太基金')),
                ('kingdom', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='國度基金')),
                ('venue', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='場地費收入')),
                ('spring', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='新春(免填)')),
                ('other', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='其他')),
                ('project', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='專案(免填)')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='合計')),
            ],
            options={
                'verbose_name': '年度奉獻統計',
                'verbose_name_plural': '年度奉獻統計',
                'db_table': 'annual_offerings',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, unique=True, verbose_name='月份')),
                ('pledge_people_count', models.IntegerField(blank=True, null=True, verbose_name='月定人數')),
                ('sunday', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='主日奉獻')),
                ('pledge', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='月定奉獻')),
                ('thanksgiving', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='感恩奉獻')),
                ('building', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='建築奉獻')),
                ('planting', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='植堂奉獻')),
                ('designated', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='指定奉獻')),
                ('mission', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='宣教&大陸奉獻')),
                ('galilee', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='加利利基金')),
                ('timothy', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='提摩太基金')),
                ('kingdom', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='國度基金')),
                ('venue', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='場地費收入')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=16, verbose_name='合計')),
            ],
            options={
                'verbose_name': '每月奉獻統計',
                'verbose_name_plural': '每月奉獻統計',
                'db_table': 'monthly_offerings',
                'ordering': ['-month'],
            },
        ),
    ]
